### ISSUE TITLE
New to android please help android.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by tsviet** [agrawalsuneet/DotLoadersPack-Android#31]
E/AndroidRuntime: FATAL EXCEPTION: Timer-0
    Process: com.aliv.client, PID: 14012
    java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
        at com.agrawalsuneet.dotsloader.loaders.LinearDotsLoader$scheduleTimer$1.run(LinearDotsLoader.kt:122)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

private fun scheduleTimer() {
        timer = Timer()
        timer?.scheduleAtFixedRate(object : TimerTask() {
            override fun run() {
                if (isSingleDir) {
                    selectedDotPos++
                    if (selectedDotPos > noOfDots) {
                        selectedDotPos = 1
                    }
                } else {
                    if (isFwdDir) {
                        selectedDotPos++
                        if (selectedDotPos == noOfDots) {
                            isFwdDir = !isFwdDir
                        }
                    } else {
                        selectedDotPos--
                        if (selectedDotPos == 1) {
                            isFwdDir = !isFwdDir
                        }
                    }
                }

                (context as Activity).runOnUiThread { invalidate() }
            }
        }, 0, animDur.toLong())
    }

**Comment by agrawalsuneet** [comment]
@tsviet I have fixed the issue here https://github.com/agrawalsuneet/DotLoadersPack-Android/pull/34
Will be releasing it soon.

**Comment by agrawalsuneet** [comment]
I have fixed the issue and released as v1.4.1
Let me know if this works for you or not and once it's verified, can you close this issue.

**Comment by akshaychavan7** [comment]
@agrawalsuneet Yes, the issue has been fixed in the new release. Thanks a lot!
